### ISSUE TITLE
502 Bad Gateway in response

### ISSUE THREAD

**Issue by cnabar** [ampproject/ampbench#101]
Hi 

I am getting 502 Bad Gateway response for some URLs - see example URL:

https://m.kohls.com/api/amp/product/prd-3056467/instant-pot-duo60-7-in-1-programmable-pressure-cooker.jsp

Entering this URL in ampbench.appspot.com shows 502 Bad Gateway error

https://ampbench.appspot.com/validate?url=https%3A%2F%2Fm.kohls.com%2Fapi%2Famp%2Fproduct%2Fprd-3056467%2Finstant-pot-duo60-7-in-1-programmable-pressure-cooker.jsp

AMP Search Test for the same URL works correctly:
https://search.google.com/test/amp?id=0L1TEKNCy2mlar1P5hynjg

**Comment by ithinkihaveacat** [comment]
Looks like part of the problem is that `kohls.com` returns 403 access denied if the user agent is not recognized:

```sh
$ curl -si -A 'MOBILE' https://www.kohls.com/product/prd-3056467/instant-pot-duo60-7-in-1-programmable-pressure-cooker.jsp | head -5
HTTP/2 403 
server: AkamaiGHost
mime-version: 1.0
content-type: text/html
content-length: 387
...
```

**Comment by ithinkihaveacat** [comment]
Deployed and verified fixed:

https://ampbench.appspot.com/validate?url=https%3A%2F%2Fm.kohls.com%2Fapi%2Famp%2Fproduct%2Fprd-3056467%2Finstant-pot-duo60-7-in-1-programmable-pressure-cooker.jsp
