### ISSUE TITLE
Validation FAILS on ampbench, while one AMP validator and Structured Data testing tool it PASSES

### ISSUE THREAD

**Issue by s-ale** [ampproject/ampbench#106]
Hi there,

I'm using the **AmpBench** online tool ( https://ampbench.appspot.com ) to test some AMP pages.

In these last days of test, however, I got some **irregular behaviours** from the tool.
Every one of these cases, can be sum up as follow:
- test of the AMP url on the "**Structured data testing tool**": OK ****(link: https://search.google.com/structured-data/testing-tool/u/0/ )
- test via the AMP method, using **#development=1** after the URL: **OK**
- test via the **AmpBench**: **FAILS**.

Here you can find an example:
https://ampbench.appspot.com/validate?url=https%3A%2F%2Fwww.centrometeoitaliano.it%2Fnotizie-meteo%2Fmeteo-importanti-conferme-giungono-in-merito-al-brusco-calo-delle-temperature-in-italia-20-2-2019-71693%2Famp%2F

The test on **MOBILE fails** (but if I try the same URL on the other tools I mentioned, it passes).

If I go on the **Amp Validator Output paragraph** (on the page I linked), I can read:

- line 1, col 0: The mandatory attribute '⚡' is missing in tag 'html'. (see https://www.ampproject.org/docs/reference/spec#required-markup)
- line 1, col 0: The parent tag of tag 'html' is '$root', but it can only be '!doctype'. (see https://www.ampproject.org/docs/reference/spec#required-markup)
- line 1, col 0: Tag or text which is only allowed inside the body section found outside of the body section.
- line 1, col 58: The tag 'y�v_�m_��d�d#"3qgui*�2��ey������ȍl�a����-g�j���8�' is disallowed.
- line 7, col 439: The tag 'd��4)���3�7' is disallowed.

...and **there is the point**: if I scroll down to the **AMP Project Validator Results** paragraph, I can see my AMP html version... and **all the errors are wrong**: 
- I can find the 'amp' attribute
- I can find the !doctype
- etc...

(As I said, both test via the AMP method, using **#development=1** and the one via the **Structured data testing tool** **PASSES**).

Sometimes, the software gives me PASS for the MOBILE versione, and **FAILS** with the **DESKTOP version** (but, again, if I check my AMP html, every tag is in the right place; and if I test the URL on "Structured Data Testing Tool" or via the #development=1, it passes).

E.g.:
https://ampbench.appspot.com/validate_ua_desktop?url=https%3A%2F%2Fwww.centrometeoitaliano.it%2Fattualita%2Foroscopo-paolo-fox-21-febbraio-2019-ariete-toro-gemelli-cancro-71695%2Famp%2F

Can you give me some tips?

Am I doing something wrong?

Or there's some trouble in the code?

Thank you very much for your wonderful work!
Regards!

Alessandro

**Comment by ithinkihaveacat** [comment]
There are very occasionally differences between the ampbench result and those of other tools because of differences in validation rules, or the actual AMP validator going out of sync. That said, right now ampbench [is reporting that that URL is valid](https://ampbench.appspot.com/validate?url=https%3A%2F%2Fwww.centrometeoitaliano.it%2Fnotizie-meteo%2Fmeteo-importanti-conferme-giungono-in-merito-al-brusco-calo-delle-temperature-in-italia-20-2-2019-71693%2Famp%2F).

Will close this for now; please re-open if you come across another URL with differing behaviour.
