### ISSUE TITLE
AMP Validator Output shows "FAIL" while AMP Project Validator Results and SDTT show "PASS"

### ISSUE THREAD

**Issue by y2x33** [ampproject/ampbench#107]
![image](https://user-images.githubusercontent.com/11724193/54578670-97187880-4a3b-11e9-810e-16026a0d5636.png)

As far as I know, `amp-story-bookend` now supports inline json according to this [issue](https://github.com/ampproject/amphtml/issues/15826), please update validation rules. Thanks.

**Comment by ithinkihaveacat** [comment]
Thanks for the report. I've updated the validator and I think this is fixed now:

https://ampbench.appspot.com/validate?url=https%3A%2F%2Fedition.cnn.com%2Fampstories%2Fentertainment%2Fthese-artists-are-in-the-elusive-egot-club

**Comment by ithinkihaveacat** [comment]
(If it doesn't, can you provide a test URL?)
