### ISSUE TITLE
Inconsistently failing documents that contain amp-skimlinks

### ISSUE THREAD

**Issue by hrkhal** [ampproject/ampbench#110]
ampbench is occasionally failing articles when they contain amp-skimlinks elements:

`The tag 'amp-skimlinks' is disallowed.`
`Custom JavaScript is not allowed. (see https://www.ampproject.org/docs/reference/spec#html-tags)"`

This isn't consistent either, if I refresh or try again it'll sometimes  pass the article and then it'll go back to failing. It's caused a lot of false flags for us since we went live with amp-skimlinks yesterday.

I've only witnessed the issue on the `raw`, `api`, `api1` and `api2` endpoints. I have not seen an article fail because of `amp-skimlinks` when hitting the standard `validate` endpoint.

**Comment by hrkhal** [comment]
It appears I have fixed this by hitting the force validator update endpoint and noting a validator change: https://ampbench.appspot.com/command_force_validator_update
 
I can no longer replicate failure due to amp-skimlinks. 

Could the validator force updates not be automated?

**Comment by ithinkihaveacat** [comment]
Sorry about that, I think there servers were in an inconsistent state. The real fix will come via #97.
