### ISSUE TITLE
Add validator section that checks multiple validators

### ISSUE THREAD

**Issue by dknecht** [ampproject/ampbench#12]
Add separate validation results for JS validator, Google Cache Validator, and Cloudflare validator.

**Comment by dknecht** [comment]
I put this as place holders.  We are going to fully document this shortly.

**Comment by dknecht** [comment]
Cloudflare has a "q" interface similar to the "c" interface on amp cache that will return json of the url in path or document that is posted. 

```
curl https://amp.cloudflare.com/q/amp.usatoday.com/story/82055560/
{"version":"1485227592804","source":"http://amp.usatoday.com/story/82055560/","valid":true}
```

```
curl -X POST --data-binary @invalid_amp.html -H 'Content-Type: text/html; charset=UTF-8' https://amp.cloudflare.com/q/
{"version":"1485227592804","source":"POST","valid":false,"errors":[{"line":13,"col":7,"code":"MANDATORY_TAG_MISSING","error":"The mandatory tag 'link rel=canonical' is missing or incorrect.","help":"https://www.ampproject.org/docs/reference/spec.html#required-markup"}]}
```

**Comment by ithinkihaveacat** [comment]
Google validator endpoint:

https://developers.google.com/amp/cache/reference/acceleratedmobilepageurl/rest/v1/ampUrls/batchGet

Example of a page that is valid according to the JS validator, but invalid according to Google's validators (e.g. https://search.google.com/test/amp, and the above API):

https://honey-soybean.glitch.me/

**Comment by ithinkihaveacat** [comment]
Closing this. Whereas #11 can be "fixed" by reading https://cdn.ampproject.org/caches.json, so far there's no machine-readable system for figuring out which validators exist, and how to query them. Also, #11 will probably be implemented by fetching the AMP URL "via" the cache, which will in effect test validation.
