### ISSUE TITLE
ampbench.appspot.com will be disabled on 31 Jan 2020

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/ampbench#126]
The team behind `ampbench` has decided to shut down the hosted version at https://ampbench.appspot.com on January 31st, 2020.

We've made this decision for two main reasons:

1. The codebase and supported tests and features are out of date. For multiple reasons, we haven't been able to find time to update and maintain it, and we'd rather deprecate the site rather than have it continue in a degraded state.
2. Various (and often better!) alternatives exist. Deprecating ampbench will hopefully spur on the creation of more sustainable alternatives.

What can I use instead?

None of these tools are a 1:1 replacement for `ampbench`, however we believe that together they cover most use cases:

- https://validator.amp.dev/ - canonical AMP validator
- https://search.google.com/test/amp - AMP and structured data validator, Google search preview
- https://search.google.com/structured-data/testing-tool - more detailed structured data testing tool
- [@ampproject/toolbox-cli](https://www.npmjs.com/package/@ampproject/toolbox-cli) - command-line tool (and npm module), performs validation and in-depth linting (of CORS headers, images, and more)
- https://github.com/ampproject/ampbench#deploying-ampbench-to-the-cloud - instructions on how to self-host ampbench on GCP and AWS

If these alternatives do not meet your needs, please use the comments below to: (1) explain how you're currently using `ampbench` and how its deprecation will disrupt your workflow; and (2) suggest some (limited!) things we could do to ease your pain.

Thanks for using `ampbench` and happy AMP development!

@ithinkihaveacat @pietergreyling @juliantoledo @labiaga

**Comment by oscarruizmrf** [comment]
Hi @ithinkihaveacat, is the whole AMP Bench project discontinued? or just the https://ampbench.appspot.com hosting?
Thanks.

**Comment by ithinkihaveacat** [comment]
@oscarruizmrf Just the hosted version. The code will remain here for the foreseeable future. (Though it won't be updated.)

**Comment by oscarruizmrf** [comment]
Thanks @ithinkihaveacat. AMP Bench was validating structure data, and validator.amp.dev is not, do you know of any alternative to integrate structure data validation in a continuous integration system?

**Comment by ithinkihaveacat** [comment]
@oscarruizmrf I haven't tried it myself, but https://www.npmjs.com/package/structured-data-testing-tool/ might help with structured data testing.

/cc @nainar

**Comment by MtDalPizzol** [comment]
Hi folks. Do you know where can I find out if my structured data is valid for the Top Story Carousel? 

Here's what happened with our sites: we were validating the AMP pages and the structured data with the 3 first tools mentioned by @ithinkihaveacat and everything was looking fine. These tools were telling us that our pages were OK. But we have vanished from Google Discover and Google News.

Then, I found AMP Bench and it told us that our Article.image and our Article.publisher.logo markup were NOT OK. I fixed the issues and we're hoping to see some better results in the next days.

At the same time, I saw this thread and now I don't know where can I get a similar validation.

**Comment by ithinkihaveacat** [comment]
@MtDalPizzol Thanks for the report. I was expecting those tools to do at least as good a job at ampbench for diagnosing schema.org problems, so there might be a bug here.

What changes did you make? Are they mentioned in the `image` and `publisher.logo` sections of https://developers.google.com/search/docs/data-types/article#amp?

**Comment by MtDalPizzol** [comment]
@ithinkihaveacat , thanks for the quick response.

We were having the following problems:

1. Our publisher logo didn't match the specs at [AMP logo guidelines](https://developers.google.com/search/docs/data-types/article#logo-guidelines). But this wasn't pointed out by any of the 3 first tools mentioned. So, I think AMP Bench helped with this. It was the only tool capable of pointing this error out. We redesign the logo to meet the specs and fixed the width and height attributes on the structured data.

2. Our Article.image was marked as an array of schema.org ImageObject's, which I expected to be valid, but only AMP Bench pointed that this wasn't the case. I changed it so that Article.image is now a single ImageObject. In this case, I'm not sure if AMP Bench is right or if it is outdated and it should accept an array. The other tools were telling us that the Article.image property was OK. We think that AMP Bench is right again because we end up looking at some other sites structured data and found out that everybody were using a single ImageObject for this field.

**Comment by ithinkihaveacat** [comment]
@MtDalPizzol Thanks for the additional info.'

Re (1), I tested <https://search.google.com/structured-data/testing-tool> and as you say it appears to not be issuing any warnings/errors if the `publisher.logo` does not match the AMP logo guidelines. I've logged a bug internally for this. (I'm not sure if that is actually causing problems, but it does seem like it should be flagging those errors.)

Re (2), I'm not sure that's an actual error. For example the article images of https://www.nytimes.com/2020/02/04/us/politics/senate-impeachment-vote.html are in an array, but the `article.image` appears in Google Search as expected.

**Comment by ithinkihaveacat** [comment]
ampbench has now been turned off; https://ampbench.appspot.com/ redirects to https://github.com/ampproject/ampbench#status.

We'll endeavour to keep the redirect working for at least 1 year. There are no plans to remove the source code from GitHub, however we will also not got to any heroics to ensure it stays around ;-).
