### ISSUE TITLE
Highlight the UA (mobile or desktop) that's being used for the set of AMP checks

### ISSUE THREAD

**Issue by micyeung** [ampproject/ampbench#13]
It'll be great if "Mobile UA" or "Desktop UA" can be highlighted to make it clear which UA is being used for the current set of AMP checks.

**Comment by pietergreyling** [comment]
@micyeung @tcmg
This is now implemented and deployed as per commit https://github.com/ampproject/ampbench/commit/c372dfe455543f747795fe1e37b72db48fa76777.

**Comment by micyeung** [comment]
Thank you Pieter!
