### ISSUE TITLE
Issues on Installing AmpBench on my PC

### ISSUE THREAD

**Issue by dock21** [ampproject/ampbench#137]
hello,

I am struggling currently with installing AMPBench on my PC. I really hope you can help me because I really love your product (the other alternatives are really not a match).

I followed the procedure : 
- I installed the package Node : node-v12.16.1-x64.msi
- then I run the git command `git clone https://github.com/ampproject/ampbench.git`
- and finally launched `npm start`.

But then when I click any url (http://localhost:8080/ for example) it redirects me to the https://github.com/ampproject/ampbench#status.

Which seems normal because the redirect-all.js script redirects everything to the https://github.com/ampproject/ampbench#status page !

So how is it suppose to work ?

I would really appreciate if you could help

thanks & regards

**Comment by ithinkihaveacat** [comment]
Oh yeah, the `master` version has that redirect in place! You need to make a change to your `package.json` so the start script runs `node ampbench_main.js`—i.e. reverse [this commit](https://github.com/ampproject/ampbench/commit/92b6137b34e2cafb76cb74a8d320ed43d832445c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

Note that ampbench might have issues running on Windows—I haven't tested that. It should work fine on macOS and Linux.

Will close this but please re-open if you have any further issues.

**Comment by dock21** [comment]
Many thanks for your quick answer.
I did what you said so `npm start` launches `node ampbench_main.js` but now I have another issue `Error: Cannot find module './amp-story/linter'`

I have tried on PC and Mac but I had the same issue.  And in fact linter is a directory, there is no script linter.js.

Could you please help ?

**Comment by ithinkihaveacat** [comment]
Uh sorry yes try running `npm install` (instead of `npm update`) to install the dependencies? (I've just updated [the instructions](https://github.com/ampproject/ampbench/blob/master/README.md#getting-the-code-and-running-it).)

**Comment by dock21** [comment]
many thanks it works !!!

FYI, it works on mac only, on PC I have an issue ont the install command but mac is good for me.
