### ISSUE TITLE
Logo size contradiction

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/ampbench#14]
[AMP logo guidelines](https://developers.google.com/search/docs/data-types/articles#amp-logo-guidelines) indicates that a valid logo must fit in a 60x600 rectangle, and either height is exactly 60 or width is exactly 600.

Currently ampbench validates a logo with a size of 40, like [this example](http://ampbench.appspot.com/validate?url=https%3A%2F%2Fbc.marfeel.com%2Fwww.maduradas.com%2Fes-en-serio-espana-seguira-apoyando-el-dialogo-en-venezuela-y-labor-mediadora-de-zapatero%2F%3Fmarfeeltn%3Damp)

**Comment by pietergreyling** [comment]
@oliverfernandez 

This is now implemented and deployed as per commit https://github.com/ampproject/ampbench/commit/11fcda344806a506111f70de5c3845a734294eae.

Please verify:
http://ampbench.appspot.com/validate?url=https://bc.marfeel.com/www.maduradas.com/es-en-serio-espana-seguira-apoyando-el-dialogo-en-venezuela-y-labor-mediadora-de-zapatero/?marfeeltn=amp

Thanks for raising this issue! //pieter
