### ISSUE TITLE
When an AMP or a canonical is being served with a noindex directive then flag it as a warning

### ISSUE THREAD

**Issue by adewale** [ampproject/ampbench#15]
Pages (AMPs and canonicals) can include directives such as the following:
`<meta content="noindex" data-app="true" name="robots" property="robots"/>`

These do NOT make them invalid but will lead to problems in AMP consumption systems such as search engines.

AMPBench should detect this and raise it as a warning ("Using noindex means that your AMPs will likely fail to be consumed by search engines").

**Comment by pietergreyling** [comment]
Implemented and deployed as per commit https://github.com/ampproject/ampbench/commit/d1424f7b1d7c94522c2f52a84716aaeb2b2baa4e. 

Please verify the following sample URLs:

With **PASS**:

1. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/explore/galaxy-wedding/
2. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/explore/easy-minecraft-cake/
3. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/explore/dark-fantasy-art/

With **WARNING**:

1. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/pin/100064422940127772/
2. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/pin/49328558393296599/
3. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/pin/441423200963212080/
4. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/pin/102175485272675716/
5. https://ampbench.appspot.com/validate?url=https://www.pinterest.com/amp/pin/157977899408556058/
