### ISSUE TITLE
Check for amphtml link showing a PASS when it doesn't exist

### ISSUE THREAD

**Issue by micyeung** [ampproject/ampbench#17]
**Desktop page:**
https://www.alibaba.com/photo-detail/Antiqued-Copper-Plated-Lobster-Claw-Swivel_60532600944.html
- Has canonical link pointing to itself, and amphtml link pointing to the m. page
- 302 redirects to m. page on a mobile user agent 

**Mobile page (that has been AMP'ed):**
https://m.alibaba.com/photo-detail/60532600944/Antiqued-Copper-Plated-Lobster-Claw-Swivel.html
- Has canonical link pointing to www. page, and does not have amphtml link

AMP Bench run on **Desktop page** with a mobile user agent shows that the check for AMP URL is PASSing with a link to the www. page. **Why is that?** The mobile page that it's redirecting to does not have a amphtml url, so looks like there's something wonky here.
http://ampbench.appspot.com/validate?url=https://www.alibaba.com/photo-detail/Antiqued-Copper-Plated-Lobster-Claw-Swivel_60532600944.html

**Comment by ithinkihaveacat** [comment]
Closing, https://m.alibaba.com/photo-detail/60532600944/Antiqued-Copper-Plated-Lobster-Claw-Swivel.html doesn't work anymore. (Also, a bit old!)
