### ISSUE TITLE
Integrate cache validation

### ISSUE THREAD

**Issue by cramforce** [ampproject/ampbench#2]
We see it pretty frequently that hosts accidentally "cloak" (based on UA) content when delivering to the AMP Cache.

It would be very useful to also check whether content passes validation on the cache for that reason.

**Comment by ithinkihaveacat** [comment]
I think this feature is now implemented:

<img width="686" alt="screenshot 2018-12-18 at 17 47 36" src="https://user-images.githubusercontent.com/51244/50172467-15eeff80-02ed-11e9-99cd-81c0edb0bd03.png">

(There are also separate tests to determine if the content can be directly retrieved via different UAs.)

Please re-open if I misunderstand!
