### ISSUE TITLE
Publisher Logo and Article Image are reported as "FAIL" while it passed SDTT

### ISSUE THREAD

**Issue by eric30** [ampproject/ampbench#25]
AMPbench would report the status of Publisher Logo and Article Image are both "FAIL, while it passed all the test by using Google Structured Data Testing Tool.

Sample Link: http://m.tamil.samayam.com/tamil-cinema/mohanlal-begins-talk-show-lal-salaam-
promises-a-socially-impactful-show/amp_articleshow/60133640.cms

AMPbench: http://ampbench.appspot.com/validate?url=http%3A%2F%2Fm.tamil.samayam.com%2Ftamil-cinema%2Fmohanlal-begins-talk-show-lal-salaam-promises-a-socially-impactful-show%2Famp_articleshow%2F60133640.cms

SDTT: https://search.google.com/structured-data/testing-tool/#url=http%3A%2F%2Fm.tamil.samayam.com%2Ftamil-cinema%2Fmohanlal-begins-talk-show-lal-salaam-promises-a-socially-impactful-show%2Famp_articleshow%2F60133640.cms

**Comment by ithinkihaveacat** [comment]
I think this is fixed now?

<img width="1168" alt="screenshot 2019-01-04 at 11 11 13" src="https://user-images.githubusercontent.com/51244/50685537-7b433000-1011-11e9-9d77-b52bcfbeac0d.png">
