### ISSUE TITLE
The ampbench validator is rejecting the new google analytics meta tag

### ISSUE THREAD

**Issue by jpettitt** [ampproject/ampbench#26]
On this page http://ampbench.appspot.com/validate?url=http%3A%2F%2Famp.kansascity.com%2Fnews%2Fpolitics-government%2Farticle73988477.html 

this tag 

`<meta name="amp-google-client-id-api" content="googleanalytics">`

 is throwing this error

![image](https://user-images.githubusercontent.com/524856/30704472-af4f1cb0-9ea7-11e7-8d72-9b4e2f7786dd.png)

However the embedded validator further down the page, the chrome validator plugin and the cdn validator all accept the tag.

**Comment by pietergreyling** [comment]
@jpettitt 
Please check again:
[http://ampbench.appspot.com/validate?url=http://www.kansascity.com/news/politics-government/article73988477.html](http://ampbench.appspot.com/validate?url=http://www.kansascity.com/news/politics-government/article73988477.html)

The validator was out of sync and can be updated online via this command URL route:
[https://ampbench.appspot.com/command_force_validator_update](https://ampbench.appspot.com/command_force_validator_update)

This is documented in the README here:
[Requesting an AMPHTML Validator reload from the CDN (https://cdn.ampproject.org/v0/validator.js)](https://github.com/ampproject/ampbench#requesting-an-amphtml-validator-reload-from-the-cdn-httpscdnampprojectorgv0validatorjs)
