### ISSUE TITLE
No robots.txt = failure because URL cannot be reached

### ISSUE THREAD

**Issue by bpaduch** [ampproject/ampbench#28]
I noticed in this [commit](https://github.com/ampproject/ampbench/commit/b83dd139a3d397a71e776466bec5654bf56d4618) that you indicate it's okay to have a 404 for no robots.txt file.  If that's the case, then I wonder too if the check valid URL for the robots.txt file should be skipped because it's causes the googlebots test to indicate failure: 

![googlebots-test-fail-ampbench](https://user-images.githubusercontent.com/1012254/32185022-67f54074-bd74-11e7-90bb-47f4238fca37.png)

Example site: https://www.ampproject.org

**Comment by pietergreyling** [comment]
@bpaduch, thanks for raising this issue!

I have implemented and deployed a fix as per this [commit](https://github.com/ampproject/ampbench/commit/d1943c3ae37e2712e76d403ae01f4a0a151342ab).

Please reopen if any further problems.

**Comment by bpaduch** [comment]
Thanks!
