### ISSUE TITLE
Spoof mobile user agent?

### ISSUE THREAD

**Issue by dandv** [ampproject/ampbench#3]
The following URL validates correctly when opened in Chrome with mobile emulation:

https://allrecipes.com/recipe/11749/chicken-pesto-a-la-lisa/amp/#development=1

When running it [against AMPBench](http://ampbench.appspot.com/validate?url=https%3A%2F%2Fallrecipes.com%2Frecipe%2F11749%2Fchicken-pesto-a-la-lisa%2Famp%2F), it is apparent that the desktop version is fetched instead, which leads to the validation being "a disaster".

**Comment by pietergreyling** [comment]
@dandv 
When I run Chrome Dev Tools with mobile emulation on: 
https://allrecipes.com/recipe/11749/chicken-pesto-a-la-lisa/amp/#development=1

I see multiple related page errors such as the following:
```
2mmcore.js:11 A Parser-blocking, cross-origin script, http://service.maxymiser.net/platform/us/api/mmpackage-1.8.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

recipe.bundled.js:1074 getRetailersByZip 
Error: No retailers foundk @ recipe.bundled.js:1074

main-bottom.bundled.js:138 
TypeError: this.$eval is not a function
    at $apply (main-bottom.bundled.js:161)
    at dispatch (main-top.bundled.js:217)
    at b1 (main-top.bundled.js:187)
    at nrWrapper ((index):47)

The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. 
You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

Failed to load resource: the server responded with a status of 503 
(Service Unavailable: Back-end server is at capacity)

XMLHttpRequest cannot load http://stats.aws.rubiconproject.com/stats/. No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://allrecipes.com' is therefore not allowed access. 
The response had HTTP status code 503.
```

Whilst the standalone AMP Validator (link on AMPBench page) reaches the page fine:
https://validator.ampproject.org/#url=https://allrecipes.com/recipe/11749/chicken-pesto-a-la-lisa/amp/

AMPBench is telling us that something might be flaky in the wider scheme of things:
http://ampbench.appspot.com/validate?url=https://allrecipes.com/recipe/11749/chicken-pesto-a-la-lisa/amp/

Any suggestions on how to improve this experience would be much appreciated.

**Comment by pietergreyling** [comment]
I am currently looking at building in more flexibility around User Agents.

**Comment by dandv** [comment]
That particular AllRecipes page is in flux, so it may fail validation at any time for good reason.

The reason I chose it as an example is because of the server-side redirect on desktop user agents.

**Comment by pietergreyling** [comment]
@dandv  
I just committed & deployed some related changes. Please see:
http://ampbench.appspot.com/validate?url=https://allrecipes.com/recipe/11749/chicken-pesto-a-la-lisa/amp/

**Comment by pietergreyling** [comment]
Closing: resolved as per: https://github.com/ampproject/ampbench/issues/3#issuecomment-253077852
