### ISSUE TITLE
Error in validation: amp status PASS when error in logo field

### ISSUE THREAD

**Issue by juanchaur1** [ampproject/ampbench#31]
When using ampbench I'm seeing that the status is ok(PASS) in both the general status as well as the sd_validation status; however, there's an error in the logo check.

Shouldn't the sd_validation fail if there's an actual error in any field (e.g: the logo)?

e.g: http://ampbench.appspot.com/api2?url=http://amp.economiadigital.es/finanzas-y-macro/cataluna-pierde-40-autonomos-al-dia_520355_102.html
![error_in_ampbench](https://user-images.githubusercontent.com/15922535/32844504-d955f5e6-ca22-11e7-9f19-23a805dd8444.png)

**Comment by ithinkihaveacat** [comment]
Closing as part of bug bankruptcy, please re-open if this is still a problem. (Please provide a different URL; there now appear to be no issues with that logo.)
