### ISSUE TITLE
Visual comparison diff between AMP and canonical

### ISSUE THREAD

**Issue by martinschierle** [ampproject/ampbench#33]
It would be great if the tool would incorporate an automated comparison of full-length screenshots of AMP and canonical. A well-made AMP site should look pretty much the same as the canonical, while big differences might indicate potential problems with AMP conversions, bounce rates etc. 
Output could be either visual, or just a number (percentage mismatch):

https://en.juffalow.com/javascript/website-screenshots-and-visual-diffs/

**Comment by ithinkihaveacat** [comment]
That would be awesome however gonna close this for now as too complicated and out of scope!

**Comment by martinschierle** [comment]
Fine with me, and thanks for looking into it. FYI - I hacked this together a while ago as stop-gap measure, and it lives here:

https://amp-visual-compare.glitch.me/
