### ISSUE TITLE
Checker for multiple amphtml links in the canonical

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/ampbench#35]
I've a somehow usual mistake that some websites do: they have multiple `<link rel="amphtml">` tags in their canonical site.

One of the main reasons I've seen is that those websites are Wordpress based sites that have two or more plugins which add  the markup.

[Here](https://mielenihmeet.fi/en-lakannut-rakastamasta-sinua-lakkasin-vain-yrittamasta/) is an example

I think makes sense that ampbench warns about this in the canonical check, and I'd like to send a PR

**Comment by pietergreyling** [comment]
Thanks @oliverfernandez!
Will have a look and get back to you :)

**Comment by pietergreyling** [comment]
Hi @oliverfernandez, 

I see what you mean from the canonical source:
view-source:https://mielenihmeet.fi/en-lakannut-rakastamasta-sinua-lakkasin-vain-yrittamasta/

Would you like to go ahead with the PR?

I will assign the issue to you. //pieter

**Comment by oliverfernandez** [comment]
@pietergreyling Of course. 

Could you confirm that this should be implemented in `ampbench_handlers.js` [here](https://github.com/ampproject/ampbench/blob/2c4296c34432e6a4eab3709291e228baf3cf7c09/ampbench_handlers.js#L145) ?

**Comment by pietergreyling** [comment]
@oliverfernandez 

The actual implementation should be in `ampbench_lib.js` in the [`fetch_and_parse_url_for_amplinks`](https://github.com/ampproject/ampbench/blob/2c4296c34432e6a4eab3709291e228baf3cf7c09/ampbench_lib.js#L980) function. 

The latter should pass back the status of the check in the `__return` object returned via the `on_parsed_callback`.

Then it can be handled in [`ampbench_handlers.js`](https://github.com/ampproject/ampbench/blob/2c4296c34432e6a4eab3709291e228baf3cf7c09/ampbench_handlers.js#L145).

**Comment by pietergreyling** [comment]
As per this [commit](https://github.com/ampproject/ampbench/commit/409effb4d58f320be73225a0aa0552af11148657), I added additional support for checking multiple amphtml links in the canonical.

I have also deployed all the changes to the production hosted instance of AMPBench.

See the following:
[http://ampbench.appspot.com/validate?url=https://mielenihmeet.fi/en-lakannut-rakastamasta-sinua-lakkasin-vain-yrittamasta/](http://ampbench.appspot.com/validate?url=https://mielenihmeet.fi/en-lakannut-rakastamasta-sinua-lakkasin-vain-yrittamasta/)
