### ISSUE TITLE
AMP Bench warns about missing ETag and informs about presence of ETag

### ISSUE THREAD

**Issue by Gregable** [ampproject/ampbench#37]
https://ampbench.appspot.com/validate?url=http%3A%2F%2Fwww.ampproject.org%2F

```
[WARNING] Site does not support either "If-Modified-Since" or "ETag" headers: these make amp serving more efficient
[WARNING] Header entry for If-Modified-Since not found
[PASS] Found header entry for ETag"eac69a0d2ab2423341565dd518ec23d4"
```

Note that in the same message we first warn that ETag headers are not set. Then state that a an ETag header was found. Site does appear to support etags.

**Comment by Gregable** [comment]
Similarly, should we warn about missing `if-modified-since` if an etag is present? It's unclear why the first warning suggests using either/or, but then the next two lines seem to suggest we are looking for both.

**Comment by ithinkihaveacat** [comment]
BBC is similar:

https://ampbench.appspot.com/validate?url=https%3A%2F%2Fwww.bbc.co.uk%2Fnews%2Famp%2Ftechnology-42787529

Both etags and if-modified-since are supported:

```sh
$ curl -D - -ksSo /dev/null -H 'if-none-match: "013b5ffa8c5b62692c49fe5c9e04541a"' https://www.bbc.co.uk/news/amp/technology-42787529
HTTP/2 304 
date: Wed, 24 Jan 2018 00:25:32 GMT
etag: "013b5ffa8c5b62692c49fe5c9e04541a"
```

```sh
$ curl -D - -ksSo /dev/null -H 'if-modified-since: Tue, 23 Jan 2018 18:19:45 GMT' https://www.bbc.co.uk/news/amp/technology-42787529
HTTP/2 304 
x-cache-action: HIT
x-cache-hits: 1
cache-control: max-age=60
date: Wed, 24 Jan 2018 00:26:18 GMT
etag: "013b5ffa8c5b62692c49fe5c9e04541a"
last-modified: Tue, 23 Jan 2018 18:19:45 GMT
```

**Comment by pietergreyling** [comment]
@Gregable @ithinkihaveacat 

Implemented and deployed a fix as per [this commit](https://github.com/ampproject/ampbench/commit/dcaf1c79661cc3993bbdef8ffdda5971a40c8ae0).

Please verify and I will close this issue. //pieter

**Comment by ithinkihaveacat** [comment]
It might not be worth implementing the full test for this, since it's somewhat common for servers to lie about supporting conditional requests, checking for the presence of the necessary headers is not sufficient.

e.g.

```sh
# ETag provided in response
$ curl -sS -D - -o /dev/null https://www.nbcnews.com/dateline/amp/homicide-investigation-begins-remains-missing-16-year-old-jholie-moussa-n842506
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
ETag: W/"9119-x8LIzeO+3n/AS2Nb862555paJTA"
Server: nginx
X-Backend-Server: newsa1blueweb02.west.nbcnd.aws
Date: Wed, 31 Jan 2018 14:56:17 GMT
Content-Length: 37145
Connection: keep-alive
Set-Cookie: akaas_NBCNews=1520002577~rv=99~id=2e515c38ee32c4baa23e9a41d0161490~rn=; path=/; Expires=Fri, 02 Mar 2018 14:56:17 GMT
```

```sh
# if-non-match provided, but 200 response
$ curl -D - -ksSo /dev/null -H 'if-none-match: W/"9119-x8LIzeO+3n/AS2Nb862555paJTA"' https://www.nbcnews.com/dateline/amp/homicide-investigation-begins-remains-missing-16-year-old-jholie-moussa-n842506
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
ETag: W/"90a4-QOL21oaNfJ6wwBsGqEAOuFXNkTQ"
...
```

**Comment by Gregable** [comment]
Looks much better. If I'm nitpicking, I would suggest that since the first line suggests either/or, we shouldn't call the missing i-m-s a warning. They do serve the same purpose, so including both is essentially redundant.

```

[PASS] Site supports either/or both "If-Modified-Since" and "ETag" headers: these make amp serving more efficient[WARNING] Header entry for If-Modified-Since not found[PASS] Found header entry for ETag"e4bfbf4a0281454c484b1c2ea278410c"
--
```

**Comment by pietergreyling** [comment]
Thanks, fair point about the either/or + warning. I will fix it.
