### ISSUE TITLE
Internal Server Error for invalid URL

### ISSUE THREAD

**Issue by Gregable** [ampproject/ampbench#38]
To reproduce:

Type into AMP Bench: `http:test` and submit.

Result: `Internal Server Error`

**Comment by pietergreyling** [comment]
This should now be fixed as per the following [commit](https://github.com/ampproject/ampbench/commit/1d737c0cfe3986ab1608ca9fb7971b453b6aa92c). 

Fix has been deployed to production hosted instance.

Verify with:
[https://ampbench.appspot.com/validate?url=http:test](https://ampbench.appspot.com/validate?url=http:test)

Please reopen if further problems.
