### ISSUE TITLE
Fix proposal - encodeUri used twice in ampbench_routes

### ISSUE THREAD

**Issue by gianmarcobrunialtimrf** [ampproject/ampbench#49]
The bad URL check is performed twice.

Globally through `app.use()`, and locally, through the `assert_url()` private function called within each and every validation endpoint. This is causing the queried URL to be encoded twice, thus resulting in 404 or 500 errors.

As `assert_url` seems to be always used in a "rule-of-thumb" fashion and contains more in-depth checks for the URL's to be validated, I'd propose to remove the global one.

I've opened a [PR](https://github.com/ampproject/ampbench/pull/48) for it.

**Comment by alexmrf** [comment]
Fixed in #48

**Comment by oliverfernandez** [comment]
Hello @pietergreyling

Do you think you could review this PR as well? We opened it some time ago.

Thanks!

**Comment by ithinkihaveacat** [comment]
Thanks for raising the issue (and the PR!).

The change looks reasonable but can you provide an example input URL that does the wrong thing? i.e. actual versus expected behavior?

**Comment by gianmarcobrunialtimrf** [comment]
Sure here's one:
Canonical: https://www.albawaba.com/ar/أخبار/المبعوث-الأممي-يلتقي-زعيم-إنفصاليي-جنوب-اليمن-1195508
AMP: http://amp.albawaba.com/ar/أخبار/المبعوث-الأممي-يلتقي-زعيم-إنفصاليي-جنوب-اليمن-1195508

**Comment by ithinkihaveacat** [comment]
Fixed, thanks!
