### ISSUE TITLE
Validator fails with error "The attribute 'animate' may not appear in tag 'amp-accordion'"

### ISSUE THREAD

**Issue by Joelsz** [ampproject/ampbench#54]
As per the documentation 'animate' is now a valid attribute for 'amp-accordion'. See here: https://www.ampproject.org/docs/reference/components/amp-accordion#animate

Please update the validator to match the current AMP framework.

**Comment by pietergreyling** [comment]
to/ @Joelsz 
cc/ @ithinkihaveacat 

AMPBench supports dynamically updating the validator via the following API:
`../command_force_validator_update`

as in:
[https://ampbench.appspot.com/command_force_validator_update](https://ampbench.appspot.com/command_force_validator_update)

or:
`curl https://ampbench.appspot.com/command_force_validator_update`

This is documented here: 
[Requesting an AMPHTML Validator reload from the CDN](https://github.com/ampproject/ampbench#requesting-an-amphtml-validator-reload-from-the-cdn-httpscdnampprojectorgv0validatorjs)

Could you please provide the AMBench URLs for the sites you are working with as tests.

**Comment by Joelsz** [comment]
That was helpful @pietergreyling.

We did it and now it is passing the tests.

It's weird though that no one has done it for the past few months (since "animate" was added to "amp-accordion")
