### ISSUE TITLE
amp-mustache src was updated

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/ampbench#56]
I am getting this error message:

```: line 26, col 4: The attribute 'src' in tag 'amp-mustache extension .js script' is set to the invalid value 'https://cdn.ampproject.org/v0/amp-mustache-0.2.js'. (see https://www.ampproject.org/docs/reference/components/amp-mustache)```

But looking at https://www.ampproject.org/docs/reference/components/amp-mustache:

```
Required Script | <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
```

**Comment by ithinkihaveacat** [comment]
Thanks for the report. Looks like the validator was out of date. I've now updated it (via https://ampbench.appspot.com/command_force_validator_update)--does it work now?

**Comment by gustavopaes** [comment]
like a charm! tks
