### ISSUE TITLE
Mention AMPBench at ampproject/amphtml -> validator/README.md

### ISSUE THREAD

**Issue by dandv** [ampproject/ampbench#6]
AMPBench should be listed somewhere at https://github.com/ampproject/amphtml/blob/master/validator/README.md, perhaps in the "Web UI" file.

**Comment by ithinkihaveacat** [comment]
I'm going to close this, partly for housekeeping, and partly because ampbench, at least in terms of pure validation, does not do anything beyond https://validator.ampproject.org (which is listed).
