### ISSUE TITLE
Update deploy process to use progressive rollout

### ISSUE THREAD

**Issue by dakkad** [ampproject/ampbench#63]
Refactor dynamic includes of AMP validate to use a fixed version. Also change the roll-out process for the pinned version to support [migrating traffic](https://cloud.google.com/appengine/docs/flexible/nodejs/migrating-traffic) to new versions to test rolling forward. 

The process should be repeated regularly to include ongoing changes to dependencies like the AMP validate dependencies rather than run-time updates which could result in unintended issues.

**Comment by ithinkihaveacat** [comment]
A progressive rollout seems like a pain to implement and document, I don't think we're gonna do anything like that in the short term! (Note that there is a staging server, although I do admit that does not move the project very far toward rollout and reliability best practices…)

I do want to fix the validator issue though; have created #97 for that.
