### ISSUE TITLE
Use amp-toolbox-cache-url to generate cache URLs

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/ampbench#70]
ampbench contains code to [generate AMP Cache URLs](https://github.com/ampproject/ampbench/blob/1d737c0cfe3986ab1608ca9fb7971b453b6aa92c/ampbench_lib.js#L1925-L1948). There's a bug in this code (it may generate `http` URLs if the AMP is `http`, instead of always generating `https`) and there's also now [an npm package that does this](https://www.npmjs.com/package/amp-toolbox-cache-url).

We should switch ampbench to using this package to fix the bug and remove some code.

/cc @dakkad @fstanis

**Comment by pietergreyling** [comment]
Fix merged and deployed as per [this commit](https://github.com/ampproject/ampbench/commit/067a2265c47a241da4afbd029c1fe0f82ac2e248).
