### ISSUE TITLE
Bad Gateway on some URLs

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/ampbench#8]
I'm consistently getting a 502 Bad Gateway error when loading https://ampbench.appspot.com/validate?url=https%3A%2F%2Fen-ae.namshi.com%2Fmen-shoes%2F. (Other URLs are loaded an validated by ampbench just fine, but for some reason this one errors.)

**Comment by pietergreyling** [comment]
@ithinkihaveacat Thanks for reporting this! Looking into it.

**Comment by pietergreyling** [comment]
@ithinkihaveacat I just deployed a fix as per https://github.com/ampproject/ampbench/commit/08c82ab4051ec7127e58643ab0c2ee04910ff985
Relevant URLs:
https://ampbench.appspot.com/validate?url=https://en-ae.namshi.com/men-shoes/
https://ampbench.appspot.com/validate?url=https://en-ae.namshi.com/_amp/men-shoes/

**Comment by ithinkihaveacat** [comment]
Works for me, thanks!
