### ISSUE TITLE
Error while starting AMP NPM package

### ISSUE THREAD

**Issue by amandv** [ampproject/ampbench#88]
> ampbench@1.0.0 start C:\Users\amanpreet.oberoi\ampbench
> node ampbench_main.js

module.js:442
    throw err;
    ^

Error: Cannot find module './amp-story/linter'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\amanpreet.oberoi\ampbench\ampbench_handlers.
js:23:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
 npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ampbench@1.0.0 start: `node ampbench_main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ampbench@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amanpreet.oberoi\AppData\Roaming\npm-cache\_logs\2018-10-1
6T09_46_17_221Z-debug.log

C:\Users\amanpreet.oberoi\ampbench>

**Comment by ithinkihaveacat** [comment]
This may be due to windows. I can't replicate this problem (e.g. via https://gitpod.io/#https://github.com/ampproject/ampbench).

Can you try installing amp-story/linter manually:

```sh
$ cd amp-story/linter
$ npm install
$ cd ../..
$ npm start
```

(If this works can try to come up with a better fix.)

**Comment by amandv** [comment]
Still no resolution

C:\ampbench\amp-story\linter>npm install

> amp-story-linter@0.0.1 prepare C:\ampbench\amp-story\linter
> $npm_execpath run update-data && tsc -p tsconfig.json --sourceMap -d --module
commonjs

'$npm_execpath' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amp-story-linter@0.0.1 prepare: `$npm_execpath run update-data && tsc -
p tsconfig.json --sourceMap -d --module commonjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amp-story-linter@0.0.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by ithinkihaveacat** [comment]
Looks like some of the recent changes are not compatible with Windows. I will attempt to make the scripts Windows compatible but for the moment your best bet might to use a Unix virtual machine, or hand translate the scripts from Unix to Windows style.

(e.g. replace `$npm_execpath` with `%npm_execpath%` or just `npm`.)

**Comment by ithinkihaveacat** [comment]
Closing this. We don't have a good way of testing on Windows, and it was never really "supported" (PRs welcome, though). 

The closest thing to a list of supported platforms are the ones Travis runs on: https://github.com/ampproject/ampbench/blob/master/.travis.yml.
